L2T22/hyperion/hyperion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path("user_auth/", include("django.contrib.auth.urls")),
    path("user_auth/", include("user_auth.urls")),
]

L2T22/hyperion/polls/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

L2T22/hyperion/user_auth/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'user_auth'

urlpatterns = [
    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('show_user/', views.show_user, name='show_user'),
    path('login/', views.login, name='login'),
    path("create_user/", views.register_user, name="register_user"),
    path('polls/', include('polls.urls'))
]

L2T22/hyperion/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

def __str__(self):
    return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

def __str__(self):
    return self.choice_text

L2T22/hyperion/user_auth/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class User_Register_Form(UserCreationForm):
    first_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username','password1','first_name')


L2T22/hyperion/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse


# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, "polls/poll.html", context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question', question})

def vote(request, question_id):
    question= get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(
            pk=request.POST['choice']
        )
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question' : question,
            'error_message' : "You didn't select a choice."
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(
            reverse('polls:results', args=(question_id,))
        )
    
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})



L2T22/hyperion/user_auth/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import User_Register_Form 

# Create your views here.
def user_login(request):
    return render(request, 'authentication/login.html')

def show_user(request):
    print(request.user.username)
    return render(request, 'authentication/user.html',{
        "username": request.user.username,
        "password": request.user.password
    })

def authenticate_user(request):
    username = request.POST['username']
    password= request.POST['password']
    user = authenticate(username=username, password = password)
    if user is None:
        return HttpResponseRedirect(
            reverse('user_auth:login')
        )
    else:
        login(request,user)
        return HttpResponseRedirect(
            reverse('user_auth:show_user')
        )
    
def register_user(request):
    if request.method == "POST":
        form = User_Register_Form(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password = password) 
            messages.success(request,("Registration completed"))
            return HttpResponseRedirect(
                reverse('user_auth:show_user')
            )
    else:
        form = User_Register_Form()
    return render(request, 'authentication/user_registration.html',{
        'form':form,
    })

L2T22/hyperion/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Poll Website</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Poll Question</h1>

        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}

            <div class="form-group">
                {% for choice in question.choice_set.all %}
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label class="form-check-label" for="choice{{ forloop.counter }}">
                        {{ choice.choice_text }}
                    </label>
                </div>
                {% endfor %}
            </div>

            <button type="submit" class="btn btn-primary">Vote</button>
        </form>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

L2T22/hyperion/polls/templates/polls/poll.html
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <a href = "{% url 'polls:detail' question.id %}/">
            {{ question.question_text }}
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

L2T22/hyperion/polls/templates/polls/results.html
<h1> {{ question.question_text }} </h1>

<ul>

    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }} -- {{ choice.votes}}
        vote{{choice.votes|pluralize}}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">
    Vote again?
</a>

L2T22/hyperion/user_auth/templates/authentication/login.html
<h1> Login as User </h1>

<form action="{% url 'user_auth:authenticate_user' %}" method="POST">
    {% csrf_token %}

    <label>Username</label>
    <input type="text" name="username" placeholder="User" required>
    <br/><br/>

    <label>Password</label>
    <input type="password" name="password" required>
    <br/><br/>

    <input type="submit" value="Login" />

</form>

L2T22/hyperion/user_auth/templates/authentication/user.html
<h1> Welcome, {{username}} </h1>

<p> Your password is {{password}}</p>

L2T22/hyperion/user_auth/templates/authentication/user_registration.html

<h1> Register User </h1>

<form method="POST" class="form-group">
    {% csrf_token %}
        {{form}}

<br></br>
    <input type="submit" value="Register" />

</form>